# Generated by Django 2.2 on 2020-10-10 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20201010_1607'),
        ('wall_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='Msg',
        ),
        migrations.RenameField(
            model_name='msg',
            old_name='message',
            new_name='msg',
        ),
    ]
